[workspace]
resolver = "3"
members = [
  "crates/owl-core",
  "crates/nat64",
  "crates/common-utils",
  "crates/owl-dns"
]

[workspace.dependencies]
anyhow = { version = "1", features = ["backtrace"] }
thiserror = "2"